### ISSUE TITLE
Alien::libsdl2 does not find system library

### ISSUE THREAD

**Issue by jjatria** [sanko/Alien-libsdl2#1]
The current alienfile does not find a system library in a Linux box (Ubuntu 18.04.5):

```
$ af probe alienfile 
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::CommandLine
Alien::Build::CommandSequence> + pkg-config --exists libsdl2
Alien::Build> error in probe (will do a share install): library not found: sdl2 at /home/jjatria/dev/perl/Alien-libsdl2/alienfile line 15.
Alien::Build> Don't panic, we will attempt a share build from source if possible.
Alien::Build> Do not file a bug unless you expected a system install to succeed.
install type: share
```

It looks like this is due to the library name and the probe hook. Removing the hook and changing the name of the library passed to PkgConfig to `sdl2` makes the alienfile work:

``` diff
diff --git a/alienfile b/alienfile
index 4397340..2969330 100644
--- a/alienfile
+++ b/alienfile
@@ -1,22 +1,12 @@
 use alienfile;
 use FFI::CheckLib qw[find_lib_or_die];
 use Config;
-plugin 'PkgConfig' => 'libsdl2';
+
+plugin 'PkgConfig' => 'sdl2';
 
 my $version = $ENV{ALIEN_LIBSDL2_VERSION} || '2.0.14';
 my $arch    = 'x86_64';
 
-meta->around_hook(
-    probe => sub {
-        my $orig  = shift;
-        my $build = shift;
-        my $type  = $orig->( $build, @_ );
-        return $type if $type eq 'share';
-        find_lib_or_die lib => sdl2 => symbol => [qw[SDL_log SDL_rect]];
-        return $type;
-    }
-);
-
 #probe sub {'share'};
 
 share {
```

The results:

```
$ af probe alienfile
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::CommandLine
Alien::Build::CommandSequence> + pkg-config --exists sdl2
Alien::Build::CommandSequence> + pkg-config --modversion sdl2
Alien::Build::CommandSequence> [output consumed by Alien::Build recipe]
install type: system
```

**Comment by sanko** [comment]
Once again, incomplete projects tend to be incomplete.

This dist is only on PAUSE to test building the library from scratch on smokers; the lib name is wrong on purpose. Seeing as there's no dist on CPAN that uses it as a prerequisite, no one should be installing it on their private systems anyway.

**Comment by jjatria** [comment]
The library is available on CPAN with a version number above 1.0 and no notice of it being experimental in any way in the documentation. If you consider this distribution to be unsuitable for people installing it on their systems, could I suggest you add that to the documentation?

**Comment by sanko** [comment]
If you're determined to continue working on SDL2, might I suggest using Alien::SDL2 instead.

**Comment by jjatria** [comment]
I have nothing against incomplete projects. Most of _my_ projects are incomplete.

Why are you so against people contributing to the projects you've made publicly available?

**Comment by sanko** [comment]
In general, I'm not.

**Comment by jjatria** [comment]
The suggestion I made in your SDL2::FFI was only that: a suggestion. I assumed that was by design, and I asked about the rationale for the design, and suggested a possible problem with it. I was ready to hear an argument in defense of your design. I was not ready to have that issue deleted without comment.

In this case, you say the distribution is on CPAN so it can be tested by smokers. Consider me a smoker then: I tried your distribution, and found an issue. I'm not saying you should remove the hook (I'm not sure why the hook is there, but I assume there is a reason). All I'm reporting to you is that, if I make those changes, it works here. I made the report to help you.

Again: I intend no disrespect. Like you, I'm interested in making games, and I am glad there are people working on SDL2. And there is nothing wrong with having personal projects you want to pursue on your own. But if that's the case, then I think what you said is probably the best thing to do: set them to private, and don't make public releases.

If you don't, you'll have people like me who are interested in your work and want to see it succeed.

**Comment by sanko** [comment]
Noted.

I'll make both private when I get to a desktop.

**Comment by jjatria** [comment]
Considering this one is already on CPAN, though, that ship might have sailed.

**Comment by sanko** [comment]
Can't wait to not receive your "Private code is still public" bug report.

**Comment by sanko** [comment]
I found a better solution.
